name: Deploy React App to EC2

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Set this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
